### ISSUE TITLE
webpack: "cannot resolve module" errors

### ISSUE THREAD

**Issue by thinklog** [mickberber/reChat#12]
Hi.
After entering the code as displayed in the tutorial and running into problems, I downloaded this github version and tried running it using webpack, as advised.
I get the following errors:
ERROR in multi main
Module not found: Error: Cannot resolve module 'babel-polyfill' in /Users/Appsmith/Development/horizon/reChat
 @ multi main

ERROR in multi main
Module not found: Error: Cannot resolve module 'eslint' in /Users/AppSmith/Development/horizon/reChat
 @ multi main

Both errors also occurred when I was trying to run the code that I had entered myself by copying it from your tutorial.

Any ideas how I can fix that would be highly appreciated.
Thanks.

**Comment by mickberber** [comment]
Hey thinklog,

It looks to me like you might not have the node_modules installed, maybe try running 
`npm install --save eslint babel-polyfill`

The current version of master has a new linting feature that will look like its throwing a bunch of errors, but they're more of suggestions rather than rules and it shouldn't break.

If you get a chance, there's a branch for each part of the tutorial. The Part 1 and Part 2 branches are stable and work.

I hope this helps, keep me posted on what happens!

**Comment by thinklog** [comment]
Hi.
I tried the different branches and the one that I did get to work was the one called horizon-work. That was after I found a webpage that - in a different context - suggested one install the following packages, which I did:
npm install babel-core babel-loader --save-dev
npm install babel-preset-es2015 --save-dev
npm install babel-preset-react --save-dev
npm install babel-preset-stage-0 --save-dev
npm install babel-polyfill --save
npm install babel-runtime --save
npm install babel-plugin-transform-runtime --save-dev

I installed all of them out of frustration, after installing the more obvious ones did not resolve the issues. I'm not sure if all of them are really needed. But with all of them installed it works, so that's really cool!

**Comment by mickberber** [comment]
Okay cool! I'm sorry you had trouble, but as long as it working that's all hat matters. When Babel 6 came out all the "extra" packages became necessary. I forgot why exactly, but I think it's because they didn't want to get to tightly coupled with react. Anywho! Happy coding!
